### ISSUE TITLE
problem sending tags

### ISSUE THREAD

**Issue by alfredocambera** [aphyr/riemann-tools#135]
I'm using riemann-health to send tagged events. Here is the command that I'm using:

    riemann-health  --tag "atrib"

The corresponding riemann log output:

    WARN [2016-01-18 08:44:43,746] worker-3 - riemann.transport.websockets - ws-handler caught; closing websocket connection.
    clj_antlr.ParseError: token recognition error at: '''
    extraneous input '=' expecting STRING
    extraneous input '=' expecting STRING
    token recognition error at: '''
            at clj_antlr.common$parse_error.invoke(common.clj:146)
            at clj_antlr.interpreted.SinglethreadedParser.parse(interpreted.clj:100)
            at clj_antlr.interpreted.ThreadLocalParser.parse(interpreted.clj:122)
            at clj_antlr.core.ParserWrapper.parse(core.clj:13)
            at clj_antlr.core$parse_STAR_.invoke(core.clj:28)
            at clj_antlr.core$parse.invoke(core.clj:35)
            at clj_antlr.core.ParserWrapper.invoke(core.clj:17)
            at riemann.query$ast.invoke(query.clj:118)
            at riemann.transport.websockets$ws_index_handler.invoke(websockets.clj:72)
            at riemann.transport.websockets$ws_handler$handle__6317$fn__6318.invoke(websockets.clj:155)
            at riemann.transport.websockets$ws_handler$handle__6317.invoke(websockets.clj:137)
            at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

It seems like a parsing error. I ran the test on a box with the following software:
    riemann-tools - 0.2.7
    OS - ubuntu 15.04 - 64 bits
    riemann -  0.2.10
    JVM - 1.8.0_66 (Oracle)

Let me know if you need further information about the issue.

Alfredo

**Comment by alfredocambera** [comment]
The error came from riemann-dash not from riemann-health. Sorry for the inconvenience, I'll close the issue.
